version: "3.8"

services:
  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    ports:
      - ${NZBHYDRA2_PORT}:5076
    volumes:
      - ${DATA_ROOT}:/data
      - ${DATA_ROOT}/config/nzbhydra2:/config
    restart: unless-stopped

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    ports:
      - ${NZBGET_PORT}:6789
    volumes:
      - ${DATA_ROOT}:/data
      - ${DATA_ROOT}/config/nzbget:/config
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr
    container_name: prowlarr
    ports:
      - ${PROWLARR_PORT}:9696
    volumes:
      - ${DATA_ROOT}:/data
      - ${DATA_ROOT}/config/prowlarr:/config
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    ports:
      - ${SONARR_PORT}:8989
    environment:
      - TZ=${TZ}
    volumes:
      - ${DATA_ROOT}:/data
      - ${DATA_ROOT}/config/sonarr:/config
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    ports:
      - ${RADARR_PORT}:7878
    environment:
      - TZ=${TZ}
    volumes:
      - ${DATA_ROOT}:/data
      - ${DATA_ROOT}/config/radarr:/config
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DATA_ROOT}:/data
      - ${DATA_ROOT}/config/readarr:/config
    ports:
      - ${READARR_PORT}:8787
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      - ${DATA_ROOT}:/data
      - ${DATA_ROOT}/config/jellyfin:/config
    devices:
      - /dev/dri:/dev/dri  # Optional for hardware acceleration
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    ports:
      - ${BAZARR_PORT}:6767
    environment:
      - TZ=${TZ}
    volumes:
      - ${DATA_ROOT}:/data
      - ${DATA_ROOT}/config/bazarr:/config
    restart: unless-stopped
