version: '3.8'

services:
  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    user: "${PUID}:${PGID}"
    container_name: nzbhydra2
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "${NZBHYDRA2_PORT}:5076"
    volumes:
      - ./config/nzbhydra2:/config
      - ${DOWNLOADS}:/data/downloads
    restart: unless-stopped

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    user: "${PUID}:${PGID}"
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "${NZBGET_PORT}:6789"
    volumes:
      - ./config/nzbget:/config
      - ${DOWNLOADS}:/data/downloads
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr
    user: "${PUID}:${PGID}"
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "${PROWLARR_PORT}:9696"
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    user: "${PUID}:${PGID}"
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "${SONARR_PORT}:8989"
    volumes:
      - ./config/sonarr:/config
      - ${DOWNLOADS}:/data/downloads
      - ${MEDIA_TV}:/data/media/tv
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    user: "${PUID}:${PGID}"
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "${RADARR_PORT}:7878"
    volumes:
      - ./config/radarr:/config
      - ${DOWNLOADS}:/data/downloads
      - ${MEDIA_MOVIES}:/data/media/movies
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "${JELLYFIN_PORT}:8096"
    volumes:
      - ./config/jellyfin:/config
      - ${MEDIA_TV}:/data/media/tv
      - ${MEDIA_MOVIES}:/data/media/movies
      - ${DOWNLOADS}:/data/downloads
    devices:
      - /dev/dri:/dev/dri  # Optional for hardware acceleration
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    user: "${PUID}:${PGID}"
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "${BAZARR_PORT}:6767"
    volumes:
      - ./config/bazarr:/config
      - ${MEDIA_TV}:/data/media/tv
      - ${MEDIA_MOVIES}:/data/media/movies
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    user: "${PUID}:${PGID}"
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "${READARR_PORT}:8787"
    volumes:
      - ./config/readarr:/config
      - ${DOWNLOADS}:/downloads
      - ${MEDIA_BOOKS}:/books
    restart: unless-stopped
